---
allowedLicenses: 
  - Apache-2.0
  - CC-BY-4.0
  - MIT
  - EPL-2.0
disallowedLicensePatterns: "API"
repositoryExceptions:
  - https://github.com/SAP/SapMachine
  - https://github.com/SAP/styleguides
  - https://github.com/SAP/abnf-test-tool
  - https://github.com/SAP/software-documentation-data-set-for-machine-translation
