---
If an open-source project has a security policy:
  - advice: >
      Open a pull request to add a security policy for the project.
    links:
      - name: About adding a security policy to a repository on GitHub
        url: https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository
      - name: An example of a security policy
        url: https://github.com/apache/nifi/blob/main/SECURITY.md
      - name: Suggest a security policy for the project
        url: ${SUGGEST_SECURITY_POLICY_ON_GITHUB}
