name: "Fosstars open source rules of play"
description: "The action checks whether open source projects follow defined rules of play."
inputs:
  report-branch:
    description: "A branch where the report is stored"
    required: true
    default: fosstars-rules-of-play
  report-file:
    description: "A file name where the report is stored"
    required: false
  fosstars-version:
    description: "A version of Fosstars"
    required: true
    default: master
  token:
    description: "A GitHub token for accessing the repository"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.report-branch }}
    - ${{ inputs.report-file }}
    - ${{ inputs.fosstars-version }}
    - ${{ inputs.token }}
