@startuml

component oss_security_rating [
OSS security
rating
]

component oss_security_score [
OSS security
score
]

component project_activity_score [
Project
activity
score
]

component project_popularity_score [
Project
popularity
score
]

component community_commitment_score [
Community
commitment
score
]

component security_awareness_score [
Security
awareness
score
]

component security_testing_score [
Security
testing
score
]

component unpatched_vulnerabilities_score [
Unpatched
vulnerabilities
score
]

component vulnerability_lifetime_score [
Vulnerability
lifetime
score
]

oss_security_rating <-- oss_security_score
oss_security_score <-- project_activity_score
oss_security_score <-- project_popularity_score
oss_security_score <-- community_commitment_score
oss_security_score <-- security_awareness_score
oss_security_score <-- security_testing_score
oss_security_score <-- unpatched_vulnerabilities_score
oss_security_score <-- vulnerability_lifetime_score

@enduml
