name: "Fosstars"
on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    name: "Security rating"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: SAP/fosstars-rating-core-action
        with:
          report-branch: fosstars-report
          token: "${{ secrets.GITHUB_TOKEN }}"
