name: "Fosstars (Security)"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    name: "Security rating"
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: Johannes-Schneider/fosstars-rating-core-action@v0.0.2-alpha
        with:
          report-branch: fosstars-report
          token: "${{ secrets.GITHUB_TOKEN }}"
