name: "Fosstars OSS security report"
on: workflow_dispatch

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    name: "Fosstars OSS security report"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/project-security-report-action
        with:
          config-file: other.yml
          report-branch: oss-security-report
          fosstars-version: v1.4.0
          token: ${{ secrets.GITHUB_TOKEN }}
          cleanup: Yes